# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdlogin < Formula
  desc "kubectl-kdlogin is a kubectl plugin that can be used to easily enable authentication flows via OIDC for a kubernetes cluster."
  homepage "https://devopstales.github.io"
  version "2.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devopstales/KubeDash/releases/download/2.0.0/kubectl-kdlogin_Darwin_arm64.tar.gz"
      sha256 "e464a6acef7323a5664350e1efa49b205d958e66ad18fa6f4cd159cc4d4ecb61"

      def install
        bin.install "kubectl-kdlogin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devopstales/KubeDash/releases/download/2.0.0/kubectl-kdlogin_Darwin_x86_64.tar.gz"
      sha256 "98158646e54bdbfc47a727c0d5828ed51aaeb7fbca4782ef91294a7f8c11a349"

      def install
        bin.install "kubectl-kdlogin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devopstales/KubeDash/releases/download/2.0.0/kubectl-kdlogin_Linux_arm64.tar.gz"
      sha256 "e4bcb42e4559b1395689400379bb6fb11c34113becfb8c31fb3e5a281924c5d0"

      def install
        bin.install "kubectl-kdlogin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devopstales/KubeDash/releases/download/2.0.0/kubectl-kdlogin_Linux_x86_64.tar.gz"
      sha256 "ab1ef67f6fdb8f183716df1e180e347ffef0211cbc9f212d1907a856ac993a2e"

      def install
        bin.install "kubectl-kdlogin"
      end
    end
  end

  conflicts_with "login"
  conflicts_with "dtlogin"
  conflicts_with "kubectl-login"
  conflicts_with "oidc-login"
end
