# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdlogin < Formula
  desc "kubectl-kdlogin is a kubectl plugin that can be used to easily enable authentication flows via OIDC for a kubernetes cluster."
  homepage "https://devopstales.github.io"
  version "3.1.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devopstales/KubeDash/releases/download/3.1.0/kubectl-kdlogin_Darwin_x86_64.tar.gz"
      sha256 "9b7d9fb85002e08c0e6235a0dd9d8ebc52eb14694f3efceb523a4dc1ce456490"

      def install
        bin.install "kubectl-kdlogin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devopstales/KubeDash/releases/download/3.1.0/kubectl-kdlogin_Darwin_arm64.tar.gz"
      sha256 "e4f0ee2b3d7d3b2cf411e3163cbd9afb5372c2a6184b5cf6e1b6fe2e6d4ba200"

      def install
        bin.install "kubectl-kdlogin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devopstales/KubeDash/releases/download/3.1.0/kubectl-kdlogin_Linux_x86_64.tar.gz"
        sha256 "820b106762857df4c450122e9ce39fffea6b910de08b2414148d36f87c8f9755"

        def install
          bin.install "kubectl-kdlogin"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devopstales/KubeDash/releases/download/3.1.0/kubectl-kdlogin_Linux_arm64.tar.gz"
        sha256 "15f00506a57fa21d2c66e3e1e5505fe4fa582aec7a4fc9444bcda674b92c765f"

        def install
          bin.install "kubectl-kdlogin"
        end
      end
    end
  end

  conflicts_with "login"
  conflicts_with "dtlogin"
  conflicts_with "kubectl-login"
  conflicts_with "oidc-login"
end
